-- =====================================================================
--  Library Management System — database schema
-- ---------------------------------------------------------------------
--  Target   : MySQL 5.7+ / MariaDB 10.3+
--  Charset  : utf8mb4 (full Unicode, including titles with diacritics)
--  Usage    : mysql -u root -p < database/library.sql
--
--  The script is idempotent: it drops and recreates the `library`
--  schema, so running it twice resets the system to a clean state.
-- =====================================================================

DROP DATABASE IF EXISTS `library`;
CREATE DATABASE `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `library`;

-- ---------------------------------------------------------------------
-- 1. admin — librarian / staff accounts
-- ---------------------------------------------------------------------
CREATE TABLE `admin` (
  `id`          INT(11)      NOT NULL AUTO_INCREMENT,
  `FullName`    VARCHAR(100) DEFAULT NULL,
  `AdminEmail`  VARCHAR(120) DEFAULT NULL,
  `UserName`    VARCHAR(60)  NOT NULL,
  `Password`    VARCHAR(255) NOT NULL COMMENT 'bcrypt hash (legacy md5 rows are upgraded on next login)',
  `updationDate` TIMESTAMP   NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_username` (`UserName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- 2. tblcategory — subject / shelf classification
-- ---------------------------------------------------------------------
CREATE TABLE `tblcategory` (
  `id`            INT(11)      NOT NULL AUTO_INCREMENT,
  `CategoryName`  VARCHAR(150) NOT NULL,
  `Status`        INT(1)       NOT NULL DEFAULT 1 COMMENT '1 = active, 0 = hidden from drop-downs',
  `CreationDate`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdationDate`  TIMESTAMP    NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_category_name` (`CategoryName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- 3. tblauthors — normalised author list
-- ---------------------------------------------------------------------
CREATE TABLE `tblauthors` (
  `id`           INT(11)      NOT NULL AUTO_INCREMENT,
  `AuthorName`   VARCHAR(150) NOT NULL,
  `creationDate` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdationDate` TIMESTAMP    NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_author_name` (`AuthorName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- 4. tblbooks — catalogue
--    `Author`   : free-text author captured by the Add Book form
--    `AuthorId` : optional FK used by the Edit Book join
--    `Count`    : number of physical copies still on the shelf
-- ---------------------------------------------------------------------
CREATE TABLE `tblbooks` (
  `id`            INT(11)      NOT NULL AUTO_INCREMENT,
  `BookName`      VARCHAR(200) NOT NULL,
  `CatId`         INT(11)      DEFAULT NULL,
  `AuthorId`      INT(11)      DEFAULT NULL,
  `Author`        VARCHAR(150) DEFAULT NULL,
  `ISBNNumber`    VARCHAR(20)  DEFAULT NULL,
  `BookPrice`     DECIMAL(10,2) DEFAULT NULL,
  `Count`         INT(11)      NOT NULL DEFAULT 0,
  `RegDate`       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdationDate`  TIMESTAMP    NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_book_isbn` (`ISBNNumber`),
  KEY `idx_book_category` (`CatId`),
  KEY `idx_book_author` (`AuthorId`),
  KEY `idx_book_name` (`BookName`),
  CONSTRAINT `fk_book_category` FOREIGN KEY (`CatId`) REFERENCES `tblcategory` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_book_author`   FOREIGN KEY (`AuthorId`) REFERENCES `tblauthors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- 5. tblstudents — members
--    `StudentId` is the human-readable library card number (SID001…),
--    generated by signup.php and used as the join key everywhere.
-- ---------------------------------------------------------------------
CREATE TABLE `tblstudents` (
  `id`            INT(11)      NOT NULL AUTO_INCREMENT,
  `StudentId`     VARCHAR(20)  NOT NULL,
  `FullName`      VARCHAR(120) NOT NULL,
  `MobileNumber`  VARCHAR(15)  DEFAULT NULL,
  `EmailId`       VARCHAR(120) NOT NULL,
  `Password`      VARCHAR(255) NOT NULL COMMENT 'bcrypt hash (legacy md5 rows are upgraded on next login)',
  `Status`        INT(1)       NOT NULL DEFAULT 1 COMMENT '1 = active, 0 = blocked',
  `fines`         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `RegDate`       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdationDate`  TIMESTAMP    NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_student_sid`   (`StudentId`),
  UNIQUE KEY `uq_student_email` (`EmailId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- 6. tblissuedbookdetails — circulation ledger
--    One row per issue event; the row is closed by setting
--    RetrunStatus = 1 and stamping ReturnDate.
--    (The column name keeps its original spelling for compatibility.)
-- ---------------------------------------------------------------------
CREATE TABLE `tblissuedbookdetails` (
  `id`            INT(11)     NOT NULL AUTO_INCREMENT,
  `BookId`        INT(11)     NOT NULL,
  `StudentID`     VARCHAR(20) NOT NULL,
  `IssuesDate`    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ReturnDate`    TIMESTAMP   NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `RetrunStatus`  INT(1)      NOT NULL DEFAULT 0 COMMENT '0 = with the student, 1 = returned',
  `fine`          DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_issue_book`    (`BookId`),
  KEY `idx_issue_student` (`StudentID`),
  KEY `idx_issue_open`    (`RetrunStatus`, `IssuesDate`),
  CONSTRAINT `fk_issue_book`    FOREIGN KEY (`BookId`) REFERENCES `tblbooks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_issue_student` FOREIGN KEY (`StudentID`) REFERENCES `tblstudents` (`StudentId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- 7. tblrequest — acquisition requests raised by students
-- ---------------------------------------------------------------------
CREATE TABLE `tblrequest` (
  `RequestId`   INT(11)      NOT NULL AUTO_INCREMENT,
  `StudentId`   VARCHAR(20)  NOT NULL,
  `BookTitle`   VARCHAR(200) NOT NULL,
  `Author`      VARCHAR(150) DEFAULT NULL,
  `Suggestion`  TEXT         DEFAULT NULL,
  `IsApproved`  VARCHAR(20)  NOT NULL DEFAULT 'Pending' COMMENT 'Pending | Approved | Not Approved',
  `RequestDate` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RequestId`),
  KEY `idx_request_student` (`StudentId`),
  CONSTRAINT `fk_request_student` FOREIGN KEY (`StudentId`) REFERENCES `tblstudents` (`StudentId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================================
--  Seed data
-- =====================================================================

-- Default librarian account — username: admin / password: Test@123
-- CHANGE THIS IMMEDIATELY AFTER THE FIRST LOGIN (Admin > Change Password).
INSERT INTO `admin` (`FullName`, `AdminEmail`, `UserName`, `Password`) VALUES
('Library Administrator', 'admin@example.edu', 'admin',
 '$2y$10$cSSSjBwEZInrpTsApL.erOLqP6yU7lK0ONlO6O.nzANFqhHEY6M4W');

INSERT INTO `tblcategory` (`CategoryName`, `Status`) VALUES
('Computer Science', 1),
('Electronics & Communication', 1),
('Mathematics', 1),
('Mechanical Engineering', 1),
('Fiction', 1);

INSERT INTO `tblauthors` (`AuthorName`) VALUES
('Thomas H. Cormen'),
('Abraham Silberschatz'),
('Andrew S. Tanenbaum'),
('Gilbert Strang'),
('Ian Goodfellow');

INSERT INTO `tblbooks` (`BookName`, `CatId`, `AuthorId`, `Author`, `ISBNNumber`, `BookPrice`, `Count`) VALUES
('Introduction to Algorithms',        1, 1, 'Thomas H. Cormen',     '9780262046305', 1200.00, 5),
('Operating System Concepts',         1, 2, 'Abraham Silberschatz', '9781118063330',  950.00, 4),
('Computer Networks',                 1, 3, 'Andrew S. Tanenbaum',  '9780132126953',  875.00, 3),
('Introduction to Linear Algebra',    3, 4, 'Gilbert Strang',       '9780980232776',  700.00, 6),
('Deep Learning',                     1, 5, 'Ian Goodfellow',       '9780262035613', 1500.00, 2);
